set(_CATKIN_CURRENT_PACKAGE "bigwork")
set(bigwork_VERSION "0.0.0")
set(bigwork_MAINTAINER "fan <fan@todo.todo>")
set(bigwork_PACKAGE_FORMAT "2")
set(bigwork_BUILD_DEPENDS "cv_bridge" "geometry_msgs" "rospy" "sensor_msgs" "std_msgs" "std_srvs" "turtlesim")
set(bigwork_BUILD_EXPORT_DEPENDS "cv_bridge" "geometry_msgs" "rospy" "sensor_msgs" "std_msgs" "std_srvs" "turtlesim")
set(bigwork_BUILDTOOL_DEPENDS "catkin")
set(bigwork_BUILDTOOL_EXPORT_DEPENDS )
set(bigwork_EXEC_DEPENDS "cv_bridge" "geometry_msgs" "rospy" "sensor_msgs" "std_msgs" "std_srvs" "turtlesim")
set(bigwork_RUN_DEPENDS "cv_bridge" "geometry_msgs" "rospy" "sensor_msgs" "std_msgs" "std_srvs" "turtlesim")
set(bigwork_TEST_DEPENDS )
set(bigwork_DOC_DEPENDS )
set(bigwork_URL_WEBSITE "")
set(bigwork_URL_BUGTRACKER "")
set(bigwork_URL_REPOSITORY "")
set(bigwork_DEPRECATED "")